import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameMonth, isValid, parseISO, startOfMonth, startOfWeek } from 'date-fns';
import { ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Dumbbell } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Anatomy, WorkoutHistory } from '@/components/workout-ui';
import { cn } from '@/lib/utils';
import { dateKey, muscleFor, type Workout } from '@/lib/workouts';
import type { WorkoutTracker } from '@/hooks/use-workouts';

export default function WorkoutCalendar({ tracker, onUndo }: { tracker: WorkoutTracker; onUndo: (entry: Workout) => void }) {
  const [params] = useSearchParams();
  const incoming = params.get('date');
  const initial = incoming && isValid(parseISO(incoming)) ? parseISO(incoming) : parseISO(tracker.today);
  const [month, setMonth] = useState<Date>(() => startOfMonth(initial));
  const [selected, setSelected] = useState<string>(() => dateKey(initial));
  const dates = useMemo(() => eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(month), { weekStartsOn: 1 }) }), [month]);
  const entriesByDate = useMemo(() => new Map(tracker.entries.map(entry => [entry.date, entry])), [tracker.entries]);
  const entry = entriesByDate.get(selected);
  const monthEntries = tracker.entries.filter(item => isSameMonth(parseISO(item.date), month));
  return <div className="page-enter space-y-6"><div className="grid gap-5 xl:grid-cols-[1fr_300px]"><section className="panel overflow-hidden p-4 sm:p-6"><div className="mb-6 flex items-center justify-between"><h2 className="text-lg font-bold">{format(month, 'MMMM yyyy')}</h2><div className="flex items-center gap-1"><Button variant="ghost" size="sm" onClick={() => { setMonth(startOfMonth(parseISO(tracker.today))); setSelected(tracker.today); }} className="mr-1 text-xs">Today</Button><Button variant="outline" size="icon" aria-label="Previous month" className="h-10 w-10 rounded-full" onClick={() => setMonth(previous => addMonths(previous, -1))}><ChevronLeft size={16} /></Button><Button variant="outline" size="icon" aria-label="Next month" className="h-10 w-10 rounded-full" onClick={() => setMonth(previous => addMonths(previous, 1))}><ChevronRight size={16} /></Button></div></div>
    <div className="mb-3 grid grid-cols-7">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => <div className="eyebrow py-2 text-center text-[9px] text-muted-foreground" key={day}>{day}</div>)}</div>
    <div className="grid grid-cols-7 gap-1.5 sm:gap-2">{dates.map(day => { const key = dateKey(day); const done = entriesByDate.get(key); const inMonth = isSameMonth(day, month); return <button key={key} aria-pressed={selected === key} aria-label={`${format(day, 'MMMM d, yyyy')}${done ? `, ${muscleFor(done.muscleId).name} completed` : ', no workout'}`} onClick={() => setSelected(key)} className={cn('flex min-h-[64px] flex-col items-center justify-start gap-2 rounded-xl border border-transparent p-2 text-xs transition hover:border-primary/40 sm:min-h-[82px] sm:items-start sm:p-3', !inMonth && 'opacity-35', key === tracker.today ? 'bg-secondary font-bold' : 'bg-secondary/40', done && 'bg-accent text-primary', selected === key && 'border-primary ring-1 ring-primary')}><span>{format(day, 'd')}</span>{done && <><span className="hidden max-w-full truncate text-[10px] font-semibold sm:block">{muscleFor(done.muscleId).name}</span><Check className="h-3.5 w-3.5 sm:hidden" /></>}</button>; })}</div>
    <div className="mt-5 flex items-center justify-between text-[10px] text-muted-foreground"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-primary" />Workout completed</span><span>{monthEntries.length} {monthEntries.length === 1 ? 'workout' : 'workouts'} this month</span></div>
  </section><section className="panel flex flex-col p-6"><p className="eyebrow text-muted-foreground">Your daily record</p><h2 className="mt-2 text-lg font-bold">{format(parseISO(selected), 'EEEE, MMM d')}</h2>{entry ? <><div className="my-6 h-44 rounded-xl bg-secondary/40 p-2"><Anatomy muscle={muscleFor(entry.muscleId)} /></div><span className="flex items-center gap-1.5 text-[11px] font-semibold text-primary"><Check size={15} />Workout completed</span><h3 className="display-type mt-3 text-5xl">{muscleFor(entry.muscleId).name}</h3><p className="mt-3 text-xs leading-relaxed text-muted-foreground">Workout {tracker.entries.findIndex(e => e.id === entry.id) + 1} of your journey. A little stronger than before.</p>{entry.id === tracker.entries.at(-1)?.id && <Button variant="outline" className="mt-6" onClick={() => onUndo(entry)}>Undo this workout</Button>}</> : <div className="flex flex-1 flex-col items-center justify-center py-10 text-center"><div className="rounded-full bg-secondary p-4"><CalendarDays size={25} className="text-muted-foreground" /></div><h3 className="mt-4 text-sm font-semibold">{selected > tracker.today ? 'A new day ahead.' : 'No workout logged.'}</h3><p className="mt-2 max-w-[210px] text-xs leading-relaxed text-muted-foreground">{selected === tracker.today ? 'Ready to show up for yourself? Your next focus is ' + tracker.next.name + '.' : selected > tracker.today ? 'Your completed workouts will appear here, one day at a time.' : 'Rest is part of progress. Your next workout will be waiting for you.'}</p>{selected === tracker.today && <Button asChild variant="link" className="mt-4 text-xs"><Link to="/">Go to today <ArrowRight size={14} /></Link></Button>}</div>}</section></div>
    <section className="panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold">Your workout history</h2><p className="mt-1 text-xs text-muted-foreground">Every body part. Every day you showed up.</p></div><Dumbbell size={20} className="text-muted-foreground" /></div><div className="mt-3 max-h-[440px] overflow-y-auto"><WorkoutHistory entries={tracker.entries} onUndo={onUndo} latestId={tracker.entries.at(-1)?.id} /></div></section>
  </div>;
}
